# Generated by Django 5.2.8 on 2025-11-23 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_cadastro_app', '0005_cliente_password_alter_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_habito', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')], max_length=10, verbose_name='Tipo do Hábito')),
                ('nome_habito', models.CharField(max_length=255, verbose_name='Nome do Hábito')),
                ('frequencia_atual_valor', models.PositiveIntegerField(verbose_name='Frequência Atual (Valor)')),
                ('frequencia_atual_periodo', models.CharField(choices=[('dia', 'Dia'), ('semana', 'Semana'), ('mes', 'Mês'), ('ano', 'Ano')], max_length=10, verbose_name='Frequência Atual (Período)')),
                ('frequencia_desejada_valor', models.PositiveIntegerField(verbose_name='Frequência Desejada (Valor)')),
                ('frequencia_desejada_periodo', models.CharField(choices=[('dia', 'Dia'), ('semana', 'Semana'), ('mes', 'Mês'), ('ano', 'Ano')], max_length=10, verbose_name='Frequência Desejada (Período)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to='login_cadastro_app.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Hábito',
                'verbose_name_plural': 'Hábitos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
