# Generated by Django 5.2.8 on 2025-11-23 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_interna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='pagina_interna.habito', verbose_name='Hábito')),
            ],
            options={
                'verbose_name': 'Registro de Atividade',
                'verbose_name_plural': 'Registros de Atividades',
                'ordering': ['-data', '-data_criacao'],
                'unique_together': {('habito', 'data')},
            },
        ),
    ]
