# Generated by Django 5.2.8 on 2025-11-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_interna', '0002_registroatividade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroAtividade',
        ),
    ]
