# Generated by Django 5.2.8 on 2025-11-25 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_interna', '0005_habito_cidade_habito_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habito',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='habito',
            name='estado',
        ),
    ]
