# Generated by Django 5.2.2 on 2025-11-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('lgpd', models.BooleanField(default=False, verbose_name='Aceita LGPD')),
                ('notificacoes', models.BooleanField(default=False, verbose_name='Aceita notificações')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
    ]
