# Generated by Django 5.2.2 on 2025-11-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro_app', '0002_revendedor_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revendedor',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Revendedor', 'verbose_name_plural': 'Revendedores'},
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='login_cadastro_app.revendedor', verbose_name='Revendedor')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
