# Generated by Django 5.2.2 on 2025-11-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro_app', '0003_alter_revendedor_options_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='revendedor',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='modelo_aparelho',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='notificacoes',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='São Paulo', max_length=100, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='idade',
            field=models.PositiveIntegerField(default=19, verbose_name='Idade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='Brasil', max_length=100, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='lgpd',
            field=models.BooleanField(default=False, verbose_name='Aceitou Termos LGPD'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_completo',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão'),
        ),
        migrations.DeleteModel(
            name='Revendedor',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
