# Generated by Django 5.2.2 on 2025-11-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro_app', '0004_remove_vendedor_revendedor_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='123456', max_length=128, verbose_name='Senha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='Indefinida', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='Brasil', max_length=100, verbose_name='País'),
        ),
    ]
