# Generated by Django 5.2.8 on 2025-11-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro_app', '0005_cliente_password_alter_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pais',
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
    ]
